# Basic Information
title: Qing Xu
# chinese_name: 
position: Ph.D.
affiliation: University of Nottingham
email: scxqx1@nottingham.ac.uk

# Search Engine Optimization (SEO)
# keywords: Qing Xu, machine learning, medical image segmentation, deep learning, vision foundation models
# description: Qing Xu is a Ph.D. student at the University of Nottingham. His research interests include Medical Image Segmentation, Deep Learning, and Vision Foundation Models.

# Links
google_scholar: https://scholar.google.com/citations?user=IzA-Ij8AAAAJ&hl=en
cv_link: assets/files/Qing_Xu_CV.pdf
github_link: https://github.com/xq141839
linkedin: https://www.linkedin.com/in/qing-xu-6556a9181/
# twitter:
# bilibili: 

# Images (e.g., your profile picture and your website's favicon)
avatar: /assets/img/profile.jpg
favicon: /assets/img/uon.png

# Footnote
enable_footnote: true

# Auto Dark Mode
auto_dark_mode: false

# Font
font: "Serif" # or "Sans Serif"

# Google Analytics ID
# google_analytics: G-SX0DZYZZVZ

# Use this project as a remote theme for GitHub Pages
remote_theme: yaoyao-liu/minimal-light

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  syntax_highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
  - temp/
